Partial Public Class Zml
    Const zns = "{zml}"
    Const importsTag = zns & "imports"
    Const usingTag = zns & "using"
    Const namespaceTag = zns & "namespace"
    Const helpersTag = zns & "helpers"
    Const injectTag = zns & "inject"
    Const layoutTag = zns & "layout"
    Const pageTag = zns & "page"
    Const modelTag = zns & "model"
    Const setTag = zns & "set"
    Const getTag = zns & "get"
    Const declareTag = zns & "declare"
    Const viewtitleTag = zns & "title"
    Const commentTag = zns & "comment"
    Const forTag = zns & "for"
    Const foreachTag = zns & "foreach"
    Const whileTag = zns & "while"
    Const ifTag = zns & "if"
    Const thenTag = zns & "then"
    Const elseifTag = zns & "elseif"
    Const elseTag = zns & "else"
    Const invokeTag = zns & "invoke"
    Const awaitTag = zns & "await"
    Const typeparamTag = zns & "typeparam"
    Const argTag = zns & "arg"
    Const lambdaTag = zns & "lambda"
    Const dotTag = zns & "dot"
    Const sectionTag = zns & "section"
    Const checkTag = zns & "check"
    Const textTag = zns & "text"
    Const viewdataTag = zns & "viewdata"
    Const displayforTag = zns & "displayfor"
    Const displaynameforTag = zns & "displaynamefor"
    Const exitTag = zns & "exit"
    Const breakTag = zns & "break"
    Const continueTag = zns & "continue"

    '-----------------------------------------
    Const nsAttr = "ns"
    Const addAttr = "add"
    Const pageAttr = "page"
    Const routeAttr = "route"
    Const objectAttr = "object"
    Const typeAttr = "type"
    Const nameAttr = "name"
    Const varAttr = "var"
    Const keyAttr = "key"
    Const valueAttr = "value"
    Const toAttr = "to"
    Const stepAttr = "step"
    Const whileattr = "while"
    Const letAttr = "let"
    Const inAttr = "in"
    Const conditionAttr = "condition"
    Const methodAttr = "method"
    Const propertyAttr = "property"
    Const indexerAttr = "indexer"
    Const returnAttr = "return"
    Const iftrueAttr = "iftrue"
    Const iffalseAttr = "iffalse"
    Const ifnullAttr = "ifnull"
    Const labelAttr = "label"

    '-----------------------------------------
    Const aspItems = "asp-items"
    Const aspFor = "asp-for"
    Const atModel = "@Model"
    Const AtPage = "@page"
    Const AtUsing = "@using"
    Const AtNamespace = "@namespace"
    Const ModelKeyword = "Model"
    Const awaitKeyword = "await"
    Const trueKeyword = "true"
    Const falseKeyword = "false"
    Const gotoKeyword = "goto"
    Const tempText = "__empty__"
    Const AtSymbole = "__AT__"
    Public Const Ampersand = "__amp__;"
    Public Const GreaterThan = "__gtn__;"
    Public Const LessThan = "__ltn__;"
    Public Const ZmlNamespacee = "xmlns:z=""zml"""
    Public Const TempRoot = "<zml " & ZmlNamespacee & ">"
    Public Const TempTagStart = "<zml>"
    Public Const TempTagEnd = "</zml>"
    Const doctypeStr = "<!DOCTYPE html>"
    Const doctypeTag = "<z:doctype html=""""/>"
End Class
